#!/bin/bash
# This is a script made to keep your Ubuntu server up to
# date placing this script to /etc/cron.weekly/autoupdate.sh.
# This script updates your server automatically and informs
# you via email if the update was succesful or not.

# Set the variable $admin_email as your email address.
admin_mail="root"

# Create a temporary path in /tmp to write a temporary log
# file. No need to edit.
tmpfile=$(mktemp)

export LANG=C
export DEBIAN_FRONTEND=noninteractive

# Run the commands to update the system and write the log
# file at the same time.

(
echo "aptitude update" 
echo "---------------" 
aptitude update  | egrep -v  "^(Hit|Ign|Get)" 
echo

echo "aptitude full-upgrade" 
echo "---------------------" 
aptitude full-upgrade -y | egrep -v "^(Reading|Building|Initializing)"
echo

echo "aptitude clean"
echo "--------------"
aptitude clean 

) >> ${tmpfile} 2>&1

# Send the temporary log via mail. The fact if the upgrade
# was succesful or not is written in the subject field.
status=""
if grep -q 'E: \|W: ' ${tmpfile} ; then
    status="failed"
else
    if grep -q '0 packages upgraded' ${tmpfile} ; then
	status="no change"
    else
	status="OK"
    fi
fi
mail -s "[aptitude] ($status) $(hostname) upgrade $(date "+%y%m%d-%H%M")" ${admin_mail} < ${tmpfile}
# Remove the temporary log file in temporary path.
rm -f ${tmpfile}
